version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    container_name: monitorex-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_HOST=redis"

  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80

  database:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 3306:3306

  redis:
    image: redis
    volumes:
      - redisData:/data
    ports:
      - 6379:6379

  laravel-echo-server:
    build:
      context: ./docker
      dockerfile: ./laravel-echo-server.dockerfile
    ports:
      - 6001:6001
    environment:
      - DEBUG=*

  php:
    build:
      context: ./
      dockerfile: ./docker/php.dockerfile

  laravel-queue-listener:
    image: monitorex_php
    volumes_from:
      - app
    working_dir: /var/www
    command: php artisan queue:listen -vvv

  npm-build:
    image: node
    volumes_from:
      - app
    working_dir: /var/www
    command: npm run watch

volumes:
  dbdata:
  redisData:
